### ISSUE TITLE
The command line argument "-c <card_index>" fails with a TypeError.

### ISSUE THREAD

**Issue by hugovangalen** [JonasSC/FTU-Mixer#3]
I am using Python version 3.6.9. If I call FTU-Mixer.py like this:
```
$ ./ftumixer.py -c 7
```

I'm receiving the following error:
```
Traceback (most recent call last):
  File "/path/to/FTU-Mixer/source/ftumixer.py", line 631, in <module>
    mixer = Mixer(card_index=args.card_index, disable_effects=args.disable_effects, mute_most_digital_routes=args.mute_most_digital_routes)
  File "/path/to/FTU-Mixer/source/ftumixer.py", line 72, in __init__
    for name in alsaaudio.mixers(self.__card_index):
TypeError: an integer is required (got type str)
```

**Comment by JonasSC** [comment]
Thank you for fixing this
